{% set name = "click-help-colors" %}
{% set version = "0.9" %}
{% set sha256 = "eb037a2dd95a9e20b3897c2b3ca57e7f6797f76a8d93f7eeedda7fcdcbc9b635" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - click

test:
  imports:
    - click_help_colors

about:
  home: https://github.com/r-m-n/click-help-colors
  license: MIT
  license_file: LICENSE.txt
  # License file missing on pypi. See: https://github.com/r-m-n/click-help-colors/issues/2
  #license_file: LICENSE.txt
  summary: Colorization of help messages in Click
  dev_url: https://github.com/r-m-n/click-help-colors
  license_family: MIT

extra:
  recipe-maintainers:
    - saketkc
